# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a0cce7a8e278906704f8987a7b88023b4482bbca70f013c7038c7f1a8aeb021287986a081af7ec10cca9ba53b32cf349d0431c9360efb437907df1ecd907f99

test:
  secret_key_base: 897f99582c0de93619b81ba2d2a6eea6416b62f745ba93af363689e01bbb6f103f72ff353b154a65fda7d2839323b51a18401a7f867c77cd55c06c963e1e9fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
